services:
  db:
    image: postgres:15
    container_name: postgres_db

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - backend


  app:
    image: todo-app
    container_name: app

    env_file:
      - .env

    environment:
      POSTGRES_HOST: db

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    networks:
      - backend

    depends_on:
      - db

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
