name: Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run pytest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: superpassword
          POSTGRES_DB: todo_db
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
          TOKEN_SECRET_KEY: d08b6af320834aff720fdff99c7dcc258fe8cc61d557ad105e237797e
        run: pytest
